<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ProblemBundle\EntityManager\ProblemManager' shared autowired service.

include_once $this->targetDirs[3].'/src/ProblemBundle/EntityManager/ProblemManager.php';

return $this->services['ProblemBundle\EntityManager\ProblemManager'] = new \ProblemBundle\EntityManager\ProblemManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'}, ${($_ = isset($this->services['knp_paginator']) ? $this->services['knp_paginator'] : $this->load('getKnpPaginatorService.php')) && false ?: '_'});
