<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'ProblemBundle\Controller\ProblemAPIController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerAwareTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Controller/Controller.php';
include_once $this->targetDirs[3].'/src/ProblemBundle/Controller/AbstractProblemController.php';
include_once $this->targetDirs[3].'/src/Library/ControllerTrait/APIControllerTrait.php';
include_once $this->targetDirs[3].'/src/ProblemBundle/Controller/ProblemAPIController.php';

return $this->services['ProblemBundle\Controller\ProblemAPIController'] = new \ProblemBundle\Controller\ProblemAPIController(${($_ = isset($this->services['ProblemBundle\EntityManager\ProblemManager']) ? $this->services['ProblemBundle\EntityManager\ProblemManager'] : $this->load('getProblemManagerService.php')) && false ?: '_'});
