<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.xvurche' shared service.

return $this->services['service_locator.xvurche'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('problemManager' => function () {
    $f = function (\ProblemBundle\EntityManager\ProblemManager $v = null) { return $v; }; return $f(${($_ = isset($this->services['ProblemBundle\EntityManager\ProblemManager']) ? $this->services['ProblemBundle\EntityManager\ProblemManager'] : $this->load('getProblemManagerService.php')) && false ?: '_'});
}));
