<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'UserBundle\EntityManager\UserManager' shared autowired service.

include_once $this->targetDirs[3].'/src/UserBundle/EntityManager/UserManager.php';

return $this->services['UserBundle\EntityManager\UserManager'] = new \UserBundle\EntityManager\UserManager(${($_ = isset($this->services['doctrine.orm.default_entity_manager']) ? $this->services['doctrine.orm.default_entity_manager'] : $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')) && false ?: '_'});
