<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPdlfvko\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPdlfvko/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerPdlfvko.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerPdlfvko\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerPdlfvko\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Pdlfvko',
    'container.build_id' => '9e415dbb',
    'container.build_time' => 1528723443,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerPdlfvko');
