<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxvgmez\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxvgmez/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXxvgmez.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXxvgmez\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXxvgmez\appProdProjectContainer(array(
    'container.build_hash' => 'Xxvgmez',
    'container.build_id' => 'b1c19d4b',
    'container.build_time' => 1527602939,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxvgmez');
