<?php

namespace ProblemBundle\Repository;

/**
 * SampleTestcaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SampleTestcaseRepository extends \Doctrine\ORM\EntityRepository
{
}
