<?php

namespace ProblemBundle\Repository;

/**
 * TestcaseInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestcaseInfoRepository extends \Doctrine\ORM\EntityRepository
{
}
